USE [master]
GO
/****** Object:  Database [Callapp]    Script Date: 01-Jun-23 22:50:50 ******/
CREATE DATABASE [Callapp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Callapp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Callapp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Callapp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Callapp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Callapp] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Callapp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Callapp] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Callapp] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Callapp] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Callapp] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Callapp] SET ARITHABORT OFF 
GO
ALTER DATABASE [Callapp] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Callapp] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Callapp] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Callapp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Callapp] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Callapp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Callapp] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Callapp] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Callapp] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Callapp] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Callapp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Callapp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Callapp] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Callapp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Callapp] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Callapp] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Callapp] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Callapp] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Callapp] SET  MULTI_USER 
GO
ALTER DATABASE [Callapp] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Callapp] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Callapp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Callapp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Callapp] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Callapp] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Callapp] SET QUERY_STORE = ON
GO
ALTER DATABASE [Callapp] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Callapp]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 01-Jun-23 22:50:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserProfiles]    Script Date: 01-Jun-23 22:50:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserProfiles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](max) NOT NULL,
	[LastName] [nvarchar](max) NOT NULL,
	[PersonalNumber] [nvarchar](11) NOT NULL,
	[UserId] [int] NOT NULL,
 CONSTRAINT [PK_UserProfiles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 01-Jun-23 22:50:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](max) NOT NULL,
	[Password] [nvarchar](max) NOT NULL,
	[Email] [nvarchar](max) NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_UserProfiles_UserId]    Script Date: 01-Jun-23 22:50:50 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_UserProfiles_UserId] ON [dbo].[UserProfiles]
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UserProfiles]  WITH CHECK ADD  CONSTRAINT [FK_UserProfiles_Users_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserProfiles] CHECK CONSTRAINT [FK_UserProfiles_Users_UserId]
GO
USE [master]
GO
ALTER DATABASE [Callapp] SET  READ_WRITE 
GO
